### ISSUE TITLE
ESDL Dual pipe service sometimes crashes

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/issues-and-project#4]
This is a deterministic issue that happens on some ESDL files. Currently we do not have an example ESDL where this happens yet. Production has been altered to log ESDL's when the service is called until the issue is reproduced.

Relevant logs:
```
2023-09-21 13:59:54,189 - PipeDuplicator - ERROR - Exception on /duplicate [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 193, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 396, in wrapper
    return function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/produces.py", line 41, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 115, in wrapper
    return function(**kwargs)
  File "/usr/src/app/swagger_server/controllers/default_controller.py", line 48, in duplicate
    esdl_string = body.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 154: invalid start byte
2023-09-21 13:59:54,189 - PipeDuplicator - ERROR - Exception on /duplicate [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 193, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 396, in wrapper
    return function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/produces.py", line 41, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 115, in wrapper
    return function(**kwargs)
  File "/usr/src/app/swagger_server/controllers/default_controller.py", line 48, in duplicate
    esdl_string = body.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 154: invalid start byte
```

**Comment by ewoudwerkman** [comment]
@edwinmatthijssen heb jij hier naar gekeken?

**Comment by edwinmatthijssen** [comment]
Nope, nog niet!   het lijkt me op zich wel handig als er een voorbeeld ESDL is waarbij dit gebeurt....

**Comment by ewoudwerkman** [comment]
Is there an ESDL available to test?
